version: "3"

services:
  db:
    image: mariadb
    restart: always
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: example
    ports:
      - 3309:3306
    networks:
      - default
    volumes:
      - /Users/mac/docker/docker-HungNA/db/mariadb/data:/var/lib/mysql

  php:
    build:
      context: "./php/"
      dockerfile: Dockerfile
    container_name: php56
    ports:
    - 9000:9000
    volumes:
      - /Users/mac/docker/docker-HungNA/htdocs:/var/www/html

  apache-hungna:
    build: "./apache/"
    container_name: apacheHungNA
    depends_on:
      - db
      - php
    networks:
      - default
    restart: always
    ports:
      - 8900:8081
    volumes:
      - /Users/mac/docker/docker-HungNA/htdocs:/var/www/html
      - /Users/mac/docker/docker-HungNA/apache/my-httpd.conf:/usr/local/apache2/conf/my-httpd.conf


